services:
  mariadb:
    container_name: mariadb
    networks:
      - inception
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - mariadb:/var/lib/mysql
    restart: unless-stopped
    expose:
      - "3306"

  nginx:
    container_name: nginx
    networks:
      - inception
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - wordpress:/var/www/wordpress
    restart: on-failure
    ports:
      - "443:443"
    depends_on:
      - wordpress

  wordpress:
    container_name: wordpress
    networks:
      - inception
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - wordpress:/var/www/wordpress
    restart: on-failure
    expose:
      - "9000"
    depends_on:
      - mariadb

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/damian/data/mariadb

  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/damian/data/wordpress

networks:
  inception:
    name: inception
    driver: bridge
